# .github/workflows/my-build.yml
name: tmate
on: 
  watch:
    types: started
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2

     - name: Setup Debug Session
       uses: csexton/debugger-action@master
